language: ruby
env:
  matrix:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_script: "sh -c 'cd spec/sample && bundle exec rake db:migrate'"
