language: ruby
env:
  matrix:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2
rvm:
  - 2.0.0-p647
  - 2.1.7
  - 2.2.3

before_script: "sh -c 'cd spec/sample && bundle exec rake db:migrate'"
